/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_iris_recorder_WebrtcProcessor */

#ifndef _Included_com_example_iris_recorder_WebrtcProcessor
#define _Included_com_example_iris_recorder_WebrtcProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_iris_recorder_WebrtcProcessor
 * Method:    init
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_iris_recorder_WebrtcProcessor_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_iris_recorder_WebrtcProcessor
 * Method:    processNoise
 * Signature: ([S)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_iris_recorder_WebrtcProcessor_processNoise
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     com_example_iris_recorder_WebrtcProcessor
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_iris_recorder_WebrtcProcessor_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
